annotations:
  category: Virtual Desktop
  images: |
    - name: kasm-api
      image: kasmweb/api:develop
    - name: kasm-manager
      image: kasmweb/manager:develop
    - name: kasm-db
      image: kasmweb/postgres:develop
    - name: kasm-proxy
      image: kasmweb/proxy:develop
    - name: kasm-guac
      image: kasmweb/kasm-guac:develop
    - name: rdp-gateway
      image: kasmweb/rdp-gateway:develop
    - name: rdp-gateway
      image: kasmweb/rdp-https-gateway:develop
apiVersion: v2
appVersion: develop
name: kasm
description: Kasm is a platform specializing in providing secure browser-based workspaces for a wide range of applications and industries. Its main goal is to provide isolated and secure environments that can be accessed via web browsers, ensuring that users can perform tasks without risking the security of their local systems.
icon: https://kasm-static-content.s3.amazonaws.com/icons/kasm-logo-small.png
home: https://kasm.com
keywords:
  - kasm
  - vdi
  - workspaces
maintainers:
  - name: Kasm Technologies, Inc.
    url: https://github.com/kasmtech/kasm-helm
version: 1.1180.0-develop
