---
# Source: kasm-single-zone/templates/db-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: kasm-test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
      restartPolicy: OnFailure
      initContainers:
        - name: db-is-ready
          image: kasmweb/api:1.17.0
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while ! pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -t 10; do echo "Waiting for DB..."; sleep 5; done
        - name: kasm-old-db-backup-set-perms
          image: kasmweb/api:1.17.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
          args:
            - |
              echo "Setting permissions and ownership for /data/kasm-db-dump..."
              chown -R 1000:1000 /data/kasm-db-dump
              chmod -R 755 /data/kasm-db-dump
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: kasm-db-dump
              mountPath: /data/kasm-db-dump
      containers:
        - name: kasm-old-db-backup-container
          image: kasmweb/api:1.17.0
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: kasm
            - name: POSTGRES_USER
              value: kasmapp
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: kasm-secrets
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              export PGPASSWORD=$POSTGRES_PASSWORD;
              pg_dump -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -Ft > /data/kasm-db-dump/kasm_dump.tar;
              ls -lah /data/kasm-db-dump/kasm_dump.tar;
          volumeMounts:
            - name: kasm-db-dump
              mountPath: /data/kasm-db-dump
              readOnly: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: kasm-db-dump
          persistentVolumeClaim:
            claimName: kasm-db-dump-pvc

---
# PVC definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-db-dump-pvc
  namespace: kasm-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
