deploymentSize: "small"
publicAddr: "kasm.contoso.com"

# Below are example settings for the Ingress configuration in OCI using the `oci-native-ingress` controller.
# Refer to the [Setting up the OCI Native Ingress Controller on OKE](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupnativeingresscontroller.htm)
# for more information.
ingress:
  # ingress.enabled -- Set ingress.enabled = true to tell OKE to use the Ingress controller to route traffic to Kasm.
  #
  enabled: true
  # ingress.ingressClassName -- Use this value to reference the pre-defined Kubernetes `ingresssClass`. To use the OCI native Ingress Class in OKE
  # you must manually create `IngressClassParameters` and an `IngressClass` in your OKE cluster. Refer to the
  # [Creating IngressClassParameters, IngressClass, and Ingress Resources](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupnativeingresscontroller-createresources.htm)
  # for more information. Also, check otu the `example-oci-ingress-class.yaml` file in this folder for example configuraitons.
  # 
  ingressClassName: oke-ingress-class
  # ingress.annotations -- The annotations below are used to configure backend and healthcheck settings for the Kasm
  # proxy service. The settings below are example settings you can use to help get started using the `Ingress` with OKE.
  # The `annotation.oci-native-ingress.oraclecloud.com/certificate-ocid` value should only be used if you manage certificates
  # independently of your OKE cluster and the certificate already exists in the OCI Certificate Management service.
  #
  annotations:
    oci-native-ingress.oraclecloud.com/backend-tls-enabled: "true"
    oci-native-ingress.oraclecloud.com/http-listener-port: "80"
    oci-native-ingress.oraclecloud.com/https-listener-port: "443"
    oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
    oci-native-ingress.oraclecloud.com/healthcheck-port: "8443"
    # Below are optional
    oci-native-ingress.oraclecloud.com/healthcheck-path: "/api/__healthcheck"
    oci-native-ingress.oraclecloud.com/healthcheck-interval-milliseconds: "30000"
    oci-native-ingress.oraclecloud.com/healthcheck-timeout-milliseconds: "3000"
    oci-native-ingress.oraclecloud.com/healthcheck-retries: "3"
    oci-native-ingress.oraclecloud.com/healthcheck-return-code: "200"
    oci-native-ingress.oraclecloud.com/healthcheck-response-regex: "{\"ok\": true}"
    # ONLY configure certificate-ocid if certificate.secretName = ""
    # Delete the line below if you want to allow `cert-manager` to manage Kasm certificates as Kubernetes secrets and not
    # have certificates managed in the OCI Certificate Management service.
    #
    oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.<region>.amaaaaaa..."
  labels: {}

route:
  enabled: false
  tls: {}
  annotations: {}
  labels: {}

proxyService:
  # proxyService.type -- Make sure the `proxyService` type = ClusterIP to tell the Helm chart to create an Ingress.
  #
  type: ClusterIP
  annotations: {}
  labels: {}

certificate:
  # certificate.secretName -- ONLY use this value if the ingress.annotations.oci-native-ingress.oraclecloud.com/certificate-ocid = "".
  # If both values are set it will cause problems in the configuration.
  #
  secretName: cert-secret-name
  # certificate.certManager -- ONLY use this value if the ingress.annotations.oci-native-ingress.oraclecloud.com/certificate-ocid = "".
  # If both values are set it will cause problems in the configuration.
  #
  certManager:
    enabled: true
    addWildCard: true
    issuerName: cert-issuer-name
    issuerKind: cert-issuer-kind
    issuerGroup: ""

database:
  standalone: false
  hostname: kasm-db
  port: 5432
  kasmDbName: kasm
  kasmDbUser: kasmapp
  postgresMasterUser: {}
  initialize_db: true
  image:
    repository: kasmweb/postgres
    tag: 1.17.0
  storage:
    # database.storage.storageClassName -- Set storageClassName for DB backend storage - if you are using the built-in Kasm DB StatefulSet.
    #
    storageClassName: storage-class-name
    retentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  annotations: {}
  resources: {}
  labels: {}

components:
  proxy:
    image:
      repository: kasmweb/proxy
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  api:
    image:
      repository: kasmweb/api
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  manager:
    image:
      repository: kasmweb/manager
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  guac:
    image:
      repository: kasmweb/kasm-guac
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpGateway:
    image:
      repository: kasmweb/rdp-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpHttpsGateway:
    image:
      repository: kasmweb/rdp-https-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  share:
    image:
      repository: kasmweb/share
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  redis:
    image:
      repository: redis
      tag: 5-alpine
    annotations: {}
    resources: {}
    labels: {}

imagePullPolicy: "IfNotPresent"
imagePullSecrets: ""
imagePullCredentials: {}
clusterDomain: "cluster.local"
affinity: {}
applySecurity: true
applyHealthChecks: true
restartPolicy: "Always"
labels: {}
nodeSelector: {}

annotations:
  certSecret: {}
  configMap: {}
  deployment: {}
  pod: {}
  service: {}
  secret: {}
  statefulSet: {}

extraLabels:
  certSecret: {}
  configMap: {}
  deployment: {}
  pod: {}
  secret: {}
  service: {}
  job: {}
  jobPod: {}
  statefulSet: {}
