{{/*
Kasm API server Deployment definition
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- $apiReplicas := ternary .Values.components.api.replicas (include "replicas.preset" (dict "node" ($constants.api.component) "size" .Values.deploymentSize)) (gt (int .Values.components.api.replicas) 0) -}}
{{- $merged := fromYaml (include "kasm.mergedValues" (dict "root" . "componentName" "api")) -}}
{{- range $idx, $zone := (include "kasm.zones" $ | fromYamlArray) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "kasm.metadata" (dict "context" $ "component" "api" "resource" "deployment" "zone" $zone.name "include" "all") | indent 2 }}
spec:
  replicas: {{ $apiReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 $apiReplicas }}
  selector:
    matchLabels:
      {{- include "kasm.metadata" (dict "context" $ "component" "api" "resource" "deployment" "zone" $zone.name "include" "match") | indent 6 }}
  template:
    metadata:
      {{- include "kasm.metadata" (dict "context" $ "component" "api" "resource" "pod" "zone" $zone.name "include" "la") | indent 6 }}
    spec:
      restartPolicy: {{ $.Values.restartPolicy }}
      {{- if $.Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets.name | default (printf "%s-image-pull-secret" $.Release.Name) }}
      {{- end }}
      {{- include "kasm.securityContext" (list $ 1000 "pod") | nindent 6 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "kasm.trustedCaInit" (list $ "api") | nindent 8 }}
        {{- include "kasm.dbIsReady" (dict "context" $ "function" "ready") | nindent 8 }}
        {{- with $merged.extraInitContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "kasm.name" (list $ "api" "container" $zone.name) }}
          image: {{ $constants.api.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          env:
            - name: PYTHONWARNINGS
              value: "ignore:datetime.datetime.utcnow:DeprecationWarning"
            - name: POSTGRES_HOST
              value: {{ $constants.db.svc | quote }}
            - name: POSTGRES_PORT
              value: {{ $constants.db.port | quote }}
            - name: POSTGRES_DB
              value: {{ $.Values.database.kasmDbName }}
            - name: POSTGRES_USER
              value: {{ $.Values.database.kasmDbUser }}
            - name: POSTGRES_POOL_SIZE
              value: "10"
            - name: POSTGRES_MAX_OVERFLOW
              value: "20"
            - name: KASM_DB_SSL
              value: "true"
            {{- include "kasm.trustedCaEnv" $ | indent 12 }}
            - name: "SERVER_ZONE_NAME"
              value: {{ $zone.name | quote }}
            - name: "KASM_EPHEMERAL"
              value: "true"
            - name: "SERVER_ID"
              value: "auto"
            - name: SERVER_HOSTNAME
              value: {{ printf "%s-%s" $constants.api.svc (include "kasm.zoneName" $zone.name) | quote }}
            {{/*
              SERVER_INTERNAL_SCHEMA is used to define the protocol the API uses to communicate with connection proxies;
              should be "http" when proxies are in the same cluster, and "https" if they are outside the cluster behind
              another NGINX proxy
            */}}
            - name: SERVER_INTERNAL_SCHEMA
              value: {{ if include "kasm.isInPrimaryRegion" (list $ $zone) }}"http"{{ else }}"https"{{ end }}
            - name: KASM_THREAD_POOL
              value: {{ $.Values.components.api.threadPool | quote }}
            - name: KASM_THREAD_POOL_LOG_INTERVAL
              value: {{ $.Values.components.api.threadPoolLogInterval | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if $.Values.database.kasmDbSecret -}}
                {{ $.Values.database.kasmDbSecret | toYaml | nindent 18 }}
                {{- else }}
                  name: {{ $constants.secrets.name }}
                  key: "db-password"
                {{- end }}
          ports:
            - name: {{ $constants.api.portName }}
              containerPort: {{ $constants.api.port }}
              protocol: TCP
          volumeMounts:
            - name: tmp-data
              mountPath: /tmp
            {{- if eq $.Values.logFormat "json" }}
            - name: kasm-api-app-config
              mountPath: /opt/kasm/current/conf/app/api/api.app.config.yaml
              subPath: api.app.config.yaml
            {{- end }}
            {{- with $merged.containerMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- include "kasm.trustedCaVolumeMounts" $ | nindent 12 }}
          {{- if $.Values.applyHealthChecks }}
          livenessProbe:
            {{- include "health.probe" (dict "root" $ "component" "api" "probeType" "livenessProbe" "type" "tcp" "portName" $constants.api.portName) | nindent 12 }}
          readinessProbe:
            {{- include "health.probe" (dict "root" $ "component" "api" "probeType" "readinessProbe" "type" "http" "path" "/api/__healthcheck" "portName" $constants.api.portName) | nindent 12 }}
          {{- end }}
          {{- if $.Values.components.api.resources }}
          resources: {{- toYaml $.Values.components.api.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" $constants.api.component "size" $.Values.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- include "kasm.securityContext" (list $ 1000 "container") | nindent 10 }}
        {{- with $merged.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp-data
          emptyDir:
            sizeLimit: 256Mi
        {{- if eq $.Values.logFormat "json" }}
        - name: kasm-api-app-config
          configMap:
            name: {{ include "kasm.name" (list $ "api-app-config") }}
        {{- end}}
      {{- with $merged.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "kasm.trustedCaVolumes" $ | nindent 8 }}
{{- end }}