{{/*
Backup the DB
*/}}
{{- if and .Values.dbManagement.initialize .Values.dbManagement.upgrade.enable -}}
  {{- fail "You cannot enable both initialize and upgrade for the DB. If you have an existing Kasm deployment you wish to upgrade, refer to our upgrade procedures - https://some.upgrade.url. Otherwise, select initialize for a new deployment." -}}
{{- end -}}
{{- $kasmSecrets := (default (printf "%s-secrets" .Release.Name) .Values.dbManagement.upgrade.oldDbSecretsName) }}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- $dbHost := "kasm-db" -}}
{{- if and .Values.database.standalone .Values.database.hostname -}}
  {{- $dbHost = .Values.database.hostname -}}
{{- else if .Values.dbManagement.upgrade.oldDbHostname -}}
  {{- $dbHost = .Values.dbManagement.upgrade.oldDbHostname -}}
{{- end }}
{{- if and .Values.dbManagement.upgrade.enable (not .Values.dbManagement.upgrade.skipBackupAndRestore) }}
# PVC definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- include "kasm.metadata" (dict "context" . "component" "pre-upgrade-backup" "resource" "pvc" "include" "all") | indent 2 }}
spec:
  {{- with .Values.dbManagement.upgrade.backupStorageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  {{- include "kasm.metadata" (dict "context" . "component" "pre-upgrade-backup" "resource" "job" "include" "all") | indent 6 }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      {{- include "kasm.metadata" (dict "context" . "component" "pre-upgrade-backup" "resource" "pod" "include" "la") | indent 6 }}
    spec:
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name | default (printf "%s-image-pull-secret" .Release.Name) }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      {{- include "kasm.securityContext" (list . 1000 "pod") | nindent 6 }}
      initContainers:
        {{- include "kasm.dbIsReady" (dict "context" . "function" "backup") | nindent 8 }}
        {{- if .Values.trustedCaBundle.enabled }}
          {{- include "kasm.trustedCaInit" (list . "api") | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "kasm.name" (list . "dbUpgrade" "container") }}
          image: {{ $constants.api.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: SERVER_HOSTNAME
              value: {{ $constants.api.svc }}
            - name: POST_DB_INIT_EXIT
              value: "true"
            - name: DB_AUTO_INITIALIZE
              value: {{ .Values.dbManagement.initialize | quote }}
            - name: POSTGRES_HOST
              value: {{ $dbHost | quote }}
            - name: POSTGRES_PORT
              value: {{ $constants.db.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.kasmDbName }}
            - name: POSTGRES_USER
              value: {{ .Values.database.kasmDbUser }}
            - name: OLD_DB_BACKUP_FILENAME
              value: {{ .Values.dbManagement.upgrade.oldDbBackupFileName }}
            {{- include "kasm.trustedCaEnv" $ | nindent 12 }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.database.kasmDbSecret -}}
                {{ .Values.database.kasmDbSecret | toYaml | nindent 18 }}
                {{- else }}
                  name: {{ $kasmSecrets }}
                  key: "db-password"
                {{- end }}
          {{- include "kasm.securityContext" (list . 1000 "container") | nindent 10 }}
          resources: {{- include "resources.preset" (dict "node" "api" "size" "small") | nindent 12 }}
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              set -e
              export PGPASSWORD=$POSTGRES_PASSWORD;
              BACKUP_FILE="/data/kasm-db-dump/$OLD_DB_BACKUP_FILENAME"
              echo "Starting backup to $BACKUP_FILE"
              pg_dump -Ft -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" --exclude-table-data=logs > "${BACKUP_FILE}"
              echo "Backup complete"
          volumeMounts:
            - name: kasm-db-dump
              mountPath: /data/kasm-db-dump
              readOnly: false
            - name: tmp-data
              mountPath: /tmp
          {{- if .Values.trustedCaBundle.enabled }}
            {{- include "kasm.trustedCaVolumeMounts" . | nindent 12 }}
          {{- end }}
      volumes:
        - name: kasm-db-dump
          persistentVolumeClaim:
            claimName: {{ include "kasm.dbUpgradeBackupPvcName" . }}
        - name: tmp-data
          emptyDir:
            sizeLimit: 256Mi
      {{- if $.Values.trustedCaBundle.enabled }}
        {{- include "kasm.trustedCaVolumes" . | nindent 8 }}
      {{- end }}
{{- end }}
