{{/*
PVC backing /tmp on the Kasm Guac pod for session recording segments.
*/}}
{{- if .Values.components.guac.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-guac-recordings" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.components.guac.recordingData.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ printf "%sGi" ((.Values.components.guac.recordingData.pvcSize | default 10) | toString) }}
{{- end }}
