{{/*
Add Image pull auth credentials
*/}}
{{- if and .Values.imagePullSecrets.enabled (ne .Values.imagePullSecrets.username "") (ne .Values.imagePullSecrets.password "") }}
{{- $secretName := .Values.imagePullSecrets.name | default (printf "%s-image-pull-secret" .Release.Name) }}
{{- $username := .Values.imagePullSecrets.username | required "imagePullSecrets.username is required" }}
{{- $password := .Values.imagePullSecrets.password | required "imagePullSecrets.password is required" }}
{{- $registry := .Values.imagePullSecrets.registry | required "imagePullSecrets.registry is required" }}
{{- $email := .Values.imagePullSecrets.email | default "" }}
{{- $auth := (printf "%s:%s" $username $password) | b64enc }}
{{- $dockerConfig := dict "auths" (dict $registry (dict "username" $username "password" $password "email" $email "auth" $auth)) }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- include "kasm.metadata" (dict "context" . "component" "image-pull" "resource" "secret" "name" $secretName "include" "all") | indent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfig | toJson | b64enc }}
{{- end }}