{{/*
Deploy the Kasm ingress if .Values.ingress.enabled set to true
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- $primaryZone := (include "kasm.primaryZone" . | fromYaml) -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "kasm.metadata" (dict "context" . "component" "proxy" "resource" "ingress" "include" "all") | indent 2 }}
spec:
{{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
{{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.publicAddr | quote }}
        {{- if eq .Values.certificate.certManager.addWildCard true }}
        - {{ printf "*.%s" $.Values.publicAddr | quote }}
        {{- end }}
        {{- with .Values.kasmZones }}
        {{- range $idx, $zone := . }}
        - {{ include "kasm.zoneProxyHostnameRequired" $zone | quote }}
        {{- end }}
        {{- end }}
      secretName: {{ .Values.certificate.secretName | default (include "kasm.name" (list . "cert-manager" "secret")) }}
  {{-  end }}
  rules:
  {{- with .Values.kasmZones }}
  {{- range $idx, $zone := . }}
  - host: {{ include "kasm.zoneProxyHostnameRequired" $zone | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ printf "%s-%s" $constants.proxy.svc (include "kasm.zoneName" $zone.name) }}
              port:
                number: {{ if eq $.Values.ingress.backendProtocol "https" }}{{ $constants.proxy.https }}{{ else }}{{ $constants.proxy.http }}{{ end }}
  {{- end }}
  {{- end }}
  - host: {{ .Values.publicAddr | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ printf "%s-%s" $constants.proxy.svc (include "kasm.zoneName" $primaryZone.name) }}
              port:
                number: {{ if eq .Values.ingress.backendProtocol "https" }}{{ $constants.proxy.https }}{{ else }}{{ $constants.proxy.http }}{{ end }}
{{- end }}