deploymentSize: "small"
publicAddr: "kasm.contoso.com"
kasmZones: []

proxyService:
  # proxyService.type -- Make sure the `proxyService` type = ClusterIP to tell the Helm chart to create an Ingress.
  #
  type: ClusterIP
  annotations: {}
  labels: {}

# Below are example settings for the Ingress configuration in OCI using the `oci-native-ingress` controller.
# Refer to the [Setting up the OCI Native Ingress Controller on OKE](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupnativeingresscontroller.htm)
# for more information.
ingress:
  # ingress.enabled -- Set ingress.enabled = true to tell OKE to use the Ingress controller to route traffic to Kasm.
  #
  enabled: true
  # ingress.tls -- Set tls value to `true` to eanble TLS configuration for the hostname defined at `publicAddr` parameter
  #
  tls: true
  # ingress.backendProtocol -- The backend protocol to for the Ingress to communicate with the Kasm proxy service.
  # Valid values: http or https
  #
  backendProtocol: https
  # ingress.ingressClassName -- Use this value to reference the pre-defined Kubernetes `ingresssClass`. To use the OCI native Ingress Class in OKE
  # you must manually create `IngressClassParameters` and an `IngressClass` in your OKE cluster. Refer to the
  # [Creating IngressClassParameters, IngressClass, and Ingress Resources](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupnativeingresscontroller-createresources.htm)
  # for more information. Also, check otu the `example-oci-ingress-class.yaml` file in this folder for example configuraitons.
  # 
  ingressClassName: oke-ingress-class
  # ingress.annotations -- The annotations below are used to configure backend and healthcheck settings for the Kasm
  # proxy service. The settings below are example settings you can use to help get started using the `Ingress` with OKE.
  # The `annotation.oci-native-ingress.oraclecloud.com/certificate-ocid` value should only be used if you manage certificates
  # independently of your OKE cluster and the certificate already exists in the OCI Certificate Management service.
  #
  annotations:
    oci-native-ingress.oraclecloud.com/http-listener-port: "80"
    oci-native-ingress.oraclecloud.com/https-listener-port: "443"
    # Below are optional
    oci-native-ingress.oraclecloud.com/backend-tls-enabled: "true"
    oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
    oci-native-ingress.oraclecloud.com/healthcheck-port: "8443"
    oci-native-ingress.oraclecloud.com/healthcheck-path: "/api/__healthcheck"
    oci-native-ingress.oraclecloud.com/healthcheck-interval-milliseconds: "30000"
    oci-native-ingress.oraclecloud.com/healthcheck-timeout-milliseconds: "3000"
    oci-native-ingress.oraclecloud.com/healthcheck-retries: "3"
    oci-native-ingress.oraclecloud.com/healthcheck-return-code: "200"
    oci-native-ingress.oraclecloud.com/healthcheck-response-regex: '{"ok": true}'
    # Use the below annotation if you wish to use the OCI Certificates service for the Load Balancer certificate instead of a Kubernetes secret
    # 
    # NOTE: Even if you use the OCI Certificates service for the Load Balancer certificate, you still must provide a Kubernetes certificate secret
    # in the `certificate.secretName` field below. This does not need to be a trusted certificate, but it's a requirement for Kasm internal service
    # communication, and Load Balancer backend communication in the event you set the `ingress.backendProtocol` to "https".
    #
    oci-native-ingress.oraclecloud.com/certificate-ocid: ocid1.certificate.oc1.iad.amaaaaaa______gabc
  labels: {}

route:
  enabled: false
  tls: {}
  annotations: {}
  labels: {}

certificate:
  # certificate.secretName -- This secret is used to store the certificate used for this deployment. The certificate can either be a trusted public certificate,
  # generated by cert-manager (use settings in `certificate.certManager`), an externally generated certificate added to Kubernetes as a
  # secret, or a self-signed certificate.
  #
  # If you use the OCI Certificate Manager service refer to the
  # [Obtain a Certificate from the Certificates Service](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupnativeingresscontroller-configuring.htm#contengsettingupnativeingresscontroller-https_tls__section_certificate_yourself)
  # documentation for additional configuration steps.
  #
  # NOTE: If you do not enable `cert-manager`, you must generate your own certificates and add them as a Kubernetes secret.
  # Refer to [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/), and 
  # [Kubernetes TLS Secret](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/)
  # for more information.
  #
  # If you use your own certificate the key and certificate MUST be named `tls.key` and `tls.crt`.
  #
  secretName: cert-secret-name
  certManager:
    enabled: true
    addWildCard: true
    issuerName: cert-issuer-name
    issuerKind: Issuer
    issuerGroup: ""
    annotations: {}
    labels: {}

database:
  standalone: false
  hostname: kasm-db
  port: 5432
  kasmDbName: kasm
  kasmDbUser: kasmapp
  kasmDbSecret: {}
  postgresMasterUser: {}
  image:
    repository: kasmweb/postgres
    tag: 1.17.0
  storage:
    storageClassName: oci-storage-class
    pvcSize: 0
    retentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  annotations: {}
  resources: {}
  labels: {}

dbManagement:
  initialize: true
  upgrade:
    enable: false
    oldDbSecretsName: "kasm-secrets"
    oldDbBackupPvc: "kasm-db-dump-pvc"
    oldDbBackupFileName: "kasm_dump.tar"
  backupCron:
    enabled: false
    pvcName: ""
    schedule: ""
    timeZone: ""
    storageClass: ""
    pvcSize: 0

components:
  proxy:
    image:
      repository: kasmweb/proxy
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  api:
    image:
      repository: kasmweb/api
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  manager:
    image:
      repository: kasmweb/manager
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  guac:
    image:
      repository: kasmweb/kasm-guac
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpGateway:
    image:
      repository: kasmweb/rdp-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpHttpsGateway:
    image:
      repository: kasmweb/rdp-https-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  share:
    image:
      repository: kasmweb/share
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  redis:
    image:
      repository: redis
      tag: 5-alpine
    annotations: {}
    resources: {}
    labels: {}

imagePullPolicy: "IfNotPresent"
imagePullSecrets:
  enabled: false
  name: ""
  type: ""
  server: ""
  username: ""
  password: ""
  email: ""
  labels: {}
  annotations: {}

clusterDomain: "cluster.local"
affinity: {}
applySecurity: true
applyHealthChecks: true
restartPolicy: "Always"
labels: {}
nodeSelector: {}

annotations:
  certSecret: {}
  configMap: {}
  cron: {}
  cronPod: {}
  deployment: {}
  pod: {}
  pvc: {}
  service: {}
  secret: {}
  statefulSet: {}

extraLabels:
  certSecret: {}
  configMap: {}
  cron: {}
  cronPod: {}
  deployment: {}
  pod: {}
  secret: {}
  service: {}
  job: {}
  jobPod: {}
  pvc: {}
  statefulSet: {}

extraObjects: []