deploymentSize: "small"
publicAddr: "kasm.contoso.com"
kasmZones: []

proxyService:
  type: ClusterIP
  annotations:
    cloud.google.com/backend-config: '{"default": "kasm-proxy-backend-config"}'
  labels: {}

# Below are example settings for the Ingress configuration in GKE.
ingress:
  # ingress.enabled -- Set the enabled value to `true` to use a pre-defined Ingress service to expose Kasm
  #
  enabled: true
  # ingress.tls -- Set tls value to `true` to eanble TLS configuration for the hostname defined at `publicAddr` parameter
  # Set to `false` to use GCP Managed Certificate instead.
  #
  tls: false
  # ingress.backendProtocol -- The backend protocol to for the Ingress to communicate with the Kasm proxy service.
  # The GKE ingress currently only working with http backend protocol with this helm chart.
  #
  backendProtocol: http
  ingressClassName: ""
  # ingress.annotations -- for a list of all GKE ingress annotation options see GCP Documentation
  # https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#summary_of_external_ingress_annotations
  #
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.global-static-ip-name: 'kasm-test'
    networking.gke.io/managed-certificates: "google-managed-cert"
  labels: {}

route:
  enabled: false
  tls: {}
  annotations: {}
  labels: {}

certificate:
  # certificate.secretName -- This secret is used to store the certificate used for this deployment. The certificate can either be a trusted public certificate,
  # generated by cert-manager (use settings in `certificate.certManager`), an externally generated certificate added to Kubernetes as a
  # secret, or a self-signed certificate.
  #
  # NOTE: If you do not enable `cert-manager`, you must generate your own certificates and add them as a Kubernetes secret.
  # Refer to [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/), and
  # [Kubernetes TLS Secret](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/)
  # for more information.
  #
  # If you use your own certificate the key and certificate MUST be named `tls.key` and `tls.crt`.
  #
  secretName: cert-secret-name
  certManager:
    enabled: true
    addWildCard: true
    issuerName: cert-issuer-name
    issuerKind: Issuer
    issuerGroup: ""
    annotations: {}
    labels: {}

database:
  standalone: false
  hostname: kasm-db
  port: 5432
  kasmDbName: kasm
  kasmDbUser: kasmapp
  kasmDbSecret: {}
  postgresMasterUser: {}
  image:
    repository: kasmweb/postgres
    tag: 1.17.0
  storage:
    storageClassName: ""
    pvcSize: 0
    retentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  annotations: {}
  resources: {}
  labels: {}

dbManagement:
  initialize: true
  upgrade:
    enable: false
    oldDbSecretsName: "kasm-secrets"
    oldDbBackupPvc: "kasm-db-dump-pvc"
    oldDbBackupFileName: "kasm_dump.tar"
  backupCron:
    enabled: false
    pvcName: ""
    schedule: ""
    timeZone: ""
    storageClass: ""
    pvcSize: 0

components:
  proxy:
    image:
      repository: kasmweb/proxy
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  api:
    image:
      repository: kasmweb/api
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  manager:
    image:
      repository: kasmweb/manager
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  guac:
    image:
      repository: kasmweb/kasm-guac
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpGateway:
    image:
      repository: kasmweb/rdp-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpHttpsGateway:
    image:
      repository: kasmweb/rdp-https-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  share:
    image:
      repository: kasmweb/share
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  redis:
    image:
      repository: redis
      tag: 5-alpine
    annotations: {}
    resources: {}
    labels: {}

imagePullPolicy: "IfNotPresent"
imagePullSecrets:
  enabled: false
  name: ""
  type: ""
  server: ""
  username: ""
  password: ""
  email: ""
  labels: {}
  annotations: {}

clusterDomain: "cluster.local"
affinity: {}
applySecurity: true
applyHealthChecks: true
restartPolicy: "Always"
labels: {}
nodeSelector: {}

annotations:
  certSecret: {}
  configMap: {}
  cron: {}
  cronPod: {}
  deployment: {}
  pod: {}
  pvc: {}
  service: {}
  secret: {}
  statefulSet: {}

extraLabels:
  certSecret: {}
  configMap: {}
  cron: {}
  cronPod: {}
  deployment: {}
  pod: {}
  secret: {}
  service: {}
  job: {}
  jobPod: {}
  pvc: {}
  statefulSet: {}

extraObjects:
  - apiVersion: cloud.google.com/v1
    kind: BackendConfig
    metadata:
      name: kasm-proxy-backend-config
    spec:
      timeoutSec: 28800
      connectionDraining:
        drainingTimeoutSec: 60
  - apiVersion: networking.gke.io/v1
    kind: ManagedCertificate
    metadata:
      name: google-managed-cert
    spec:
      domains:
        - kasm.contoso.com