deploymentSize: "small"
publicAddr: "kasm.contoso.com"

ingress:
  enabled: true
  ingressClassName: eks-ingress-class
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: kasm-ingress-lb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    ## Below are optional
    alb.ingress.kubernetes.io/ssl-redirect: true
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    alb.ingress.kubernetes.io/subnets: '["subnet-01234567890abcdef", "subnet-109876543210fedcba"]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account-id>:certificate/<certificate-id>"
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:<region>:<account-id>:<regional|global>/webacl/<acl-name>/<waf-id>"
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-port: 8443
    alb.ingress.kubernetes.io/healthcheck-path: "/api/__healthcheck"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 30
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 3
    alb.ingress.kubernetes.io/healthy-threshold-count: 2
    alb.ingress.kubernetes.io/unhealthy-threshold-count: 3
    alb.ingress.kubernetes.io/success-codes: 200
  labels: {}

route:
  enabled: false
  tls: {}
  annotations: {}
  labels: {}

# proxyService -- Configure the external-facing service type to use.
# Allowed service types: ClusterIP or LoadBalancer
#
# The service.annotations defined here only apply to the `proxy` service. If you wish to apply annotations
# to all services, use the annotations.service value at the bottom of this chart.
#
# NOTE: If ingress.enabled or route.enabled set to `true` service.type MUST be set to `ClusterIP`.
#
proxyService:
  type: ClusterIP
  annotations: {}
  labels: {}

certificate:
  # certificate.secretName -- Set the secret name where the certificate is stored.
  # This secret name will store a certificate created by `cert-manager` if you set `cert-manager.enabled` to true
  #
  secretName: cert-secret-name
  # certificate.certManager -- For additional cert-manager configuration/deployment information refer to the online documentation
  # [Cert Manager Docs](https://cert-manager.io/v1.1-docs/installation/kubernetes/). 
  # 
  # NOTE: If you do not enable `cert-manager`, you must generate your own certificates and add them as a Kubernetes secret.
  # Refer to [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/), and 
  # [Kubernetes TLS Secret](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/)
  # for more information.
  #
  certManager:
    enabled: true
    addWildCard: true
    issuerName: cert-issuer-name
    issuerKind: cert-issuer-kind
    issuerGroup: ""

database:
  standalone: false
  hostname: kasm-db
  port: 5432
  kasmDbName: kasm
  kasmDbUser: kasmapp
  postgresMasterUser: {}
  initialize_db: true
  image:
    repository: kasmweb/postgres
    tag: 1.17.0
  storage:
    # database.storage.storageClassName -- Select a storage class here suitable to your deployment requierments. Something
    # shared across your workers, such as an NFS backend would be useful to allow the DB to migrate to handle Node maintenance
    #
    storageClassName: storage-class-name
    retentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  annotations: {}
  resources: {}
  labels: {}

components:
  proxy:
    image:
      repository: kasmweb/proxy
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  api:
    image:
      repository: kasmweb/api
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  manager:
    image:
      repository: kasmweb/manager
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  guac:
    image:
      repository: kasmweb/kasm-guac
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpGateway:
    image:
      repository: kasmweb/rdp-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpHttpsGateway:
    image:
      repository: kasmweb/rdp-https-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  share:
    image:
      repository: kasmweb/share
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  redis:
    image:
      repository: redis
      tag: 5-alpine
    annotations: {}
    resources: {}
    labels: {}

imagePullPolicy: "IfNotPresent"
imagePullSecrets: ""
imagePullCredentials: {}
clusterDomain: "cluster.local"
affinity: {}
applySecurity: true
applyHealthChecks: true
restartPolicy: "Always"
labels: {}
nodeSelector: {}

annotations:
  certSecret: {}
  configMap: {}
  deployment: {}
  pod: {}
  service: {}
  secret: {}
  statefulSet: {}

extraLabels:
  certSecret: {}
  configMap: {}
  deployment: {}
  pod: {}
  secret: {}
  service: {}
  job: {}
  jobPod: {}
  statefulSet: {}
