#!/usr/bin/env python3
"""Sync chart/app version references across Chart.yaml and README.md.

Locations updated:
  - charts/kasm-helm/Chart.yaml: `version:` and `appVersion:`
  - README.md: badge line, both `helm install --version` snippets, and the
    "This branch (...) is the ... release" sentence in ## Versioning.
  - charts/kasm-helm/values.yaml: `useImageTags:`, set to "<app version>-rolling"
    (or literal "develop" when APP_VERSION is "develop").

charts/kasm-helm/README.md is intentionally NOT touched here - it is fully
regenerated by `helm-docs` from Chart.yaml + values.yaml (see `make readme`).

APP_VERSION is derived from CHART_VERSION when not given explicitly:
  - Take the middle dot-component of CHART_VERSION (e.g. "1190" in
    "1.1190.2"). First digit = major, last digit = patch, middle digits =
    minor. "1190" -> "1.19.0", "1200" -> "1.20.0", "1181" -> "1.18.1".
  - If CHART_VERSION has a `-develop` (or any `-<suffix>`) prerelease tag,
    APP_VERSION is the literal string "develop".
"""
import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CHART_YAML = REPO_ROOT / "charts" / "kasm-helm" / "Chart.yaml"
VALUES_YAML = REPO_ROOT / "charts" / "kasm-helm" / "values.yaml"
ROOT_README = REPO_ROOT / "README.md"

CHART_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(-[0-9A-Za-z.-]+)?$")


def derive_app_version(chart_version: str) -> str:
    m = CHART_VERSION_RE.match(chart_version)
    if not m:
        raise ValueError(f"CHART_VERSION {chart_version!r} is not in MAJOR.MIDDLE.PATCH[-suffix] form")
    _major, middle, _patch, suffix = m.groups()
    if suffix:
        return "develop"
    if len(middle) < 3:
        raise ValueError(f"CHART_VERSION middle component {middle!r} must be at least 3 digits (major+minor+patch)")
    return f"{middle[0]}.{middle[1:-1]}.{middle[-1]}"


def release_major_minor(chart_version: str) -> str:
    """Kasm release line (e.g. '1.20') targeted by this chart version, ignoring any -develop suffix."""
    m = CHART_VERSION_RE.match(chart_version)
    if not m:
        raise ValueError(f"CHART_VERSION {chart_version!r} is not in MAJOR.MIDDLE.PATCH[-suffix] form")
    _major, middle, _patch, _suffix = m.groups()
    if len(middle) < 2:
        raise ValueError(f"CHART_VERSION middle component {middle!r} must be at least 2 digits (major+minor)")
    return f"{middle[0]}.{middle[1:-1]}"


def update_chart_yaml(chart_version: str, app_version: str) -> None:
    text = CHART_YAML.read_text(encoding="utf-8")
    text, n_version = re.subn(r"^version: .*$", f"version: {chart_version}", text, flags=re.M)
    text, n_app = re.subn(r"^appVersion: .*$", f"appVersion: {app_version}", text, flags=re.M)
    if n_version != 1 or n_app != 1:
        raise RuntimeError(f"expected exactly one version/appVersion line in {CHART_YAML}, found {n_version}/{n_app}")
    CHART_YAML.write_text(text, encoding="utf-8")


def derive_use_image_tags(app_version: str) -> str:
    if app_version == "develop":
        return "develop"
    return f"{app_version}-rolling"


def update_values_yaml(app_version: str) -> None:
    use_image_tags = derive_use_image_tags(app_version)
    text = VALUES_YAML.read_text(encoding="utf-8")
    text, n = re.subn(r'^useImageTags: .*$', f'useImageTags: "{use_image_tags}"', text, flags=re.M)
    if n != 1:
        raise RuntimeError(f"expected exactly one useImageTags line in {VALUES_YAML}, found {n}")
    VALUES_YAML.write_text(text, encoding="utf-8")


def branch_sentence(chart_version: str, app_version: str) -> str:
    if app_version == "develop":
        return (
            f"This branch (`{chart_version}` / app `develop`) is the developer preview "
            f"for the upcoming **{release_major_minor(chart_version)}** release."
        )
    return (
        f"This branch (`{chart_version}` / app `{app_version}`) is the stable release "
        f"for Kasm Workspaces **{app_version}**."
    )


def shields_escape(value: str) -> str:
    """shields.io badge segments escape literal hyphens as double-hyphens."""
    return value.replace("-", "--")


def update_root_readme(chart_version: str, app_version: str) -> None:
    text = ROOT_README.read_text(encoding="utf-8")

    chart_badge = shields_escape(chart_version)
    app_badge = shields_escape(app_version)
    text, n_badge = re.subn(
        r"!\[Version: [^\]]*\]\(https://img\.shields\.io/badge/Version-[^)]*-informational\?style=flat-square\) "
        r"!\[AppVersion: [^\]]*\]\(https://img\.shields\.io/badge/AppVersion-[^)]*-informational\?style=flat-square\)",
        f"![Version: {chart_version}](https://img.shields.io/badge/Version-{chart_badge}-informational?style=flat-square) "
        f"![AppVersion: {app_version}](https://img.shields.io/badge/AppVersion-{app_badge}-informational?style=flat-square)",
        text,
    )
    if n_badge != 1:
        raise RuntimeError(f"expected exactly one badge line in {ROOT_README}, found {n_badge}")

    text, n_install = re.subn(r"--version [^\s\\]+", f"--version {chart_version}", text)
    if n_install != 2:
        raise RuntimeError(f"expected exactly two '--version' install snippets in {ROOT_README}, found {n_install}")

    text, n_branch = re.subn(
        r"This branch \(`[^`]*` / app `[^`]*`\)[^\n]*\.",
        branch_sentence(chart_version, app_version),
        text,
    )
    if n_branch != 1:
        raise RuntimeError(f"expected exactly one 'This branch (...)' sentence in {ROOT_README}, found {n_branch}")

    ROOT_README.write_text(text, encoding="utf-8")


def read_current_chart_version() -> tuple[str, str]:
    text = CHART_YAML.read_text(encoding="utf-8")
    version = re.search(r"^version: (.*)$", text, re.M).group(1).strip()
    app_version = re.search(r"^appVersion: (.*)$", text, re.M).group(1).strip()
    return version, app_version


def check() -> int:
    """Verify README.md and values.yaml's useImageTags match the committed Chart.yaml."""
    chart_version, app_version = read_current_chart_version()

    before_readme = ROOT_README.read_text(encoding="utf-8")
    update_root_readme(chart_version, app_version)
    after_readme = ROOT_README.read_text(encoding="utf-8")
    if before_readme != after_readme:
        ROOT_README.write_text(before_readme, encoding="utf-8")
        print(
            f"ERROR: README.md version references are out of sync with charts/kasm-helm/Chart.yaml "
            f"(chart={chart_version}, app={app_version}).",
            file=sys.stderr,
        )
        print("Run 'make readme CHART_VERSION=<version>' to regenerate, then commit the result.", file=sys.stderr)
        return 1

    before_values = VALUES_YAML.read_text(encoding="utf-8")
    update_values_yaml(app_version)
    after_values = VALUES_YAML.read_text(encoding="utf-8")
    if before_values != after_values:
        VALUES_YAML.write_text(before_values, encoding="utf-8")
        print(
            f"ERROR: charts/kasm-helm/values.yaml useImageTags is out of sync with charts/kasm-helm/Chart.yaml "
            f"(app={app_version}, expected useImageTags={derive_use_image_tags(app_version)!r}).",
            file=sys.stderr,
        )
        return 1

    print(f"OK: README.md and values.yaml version references match Chart.yaml (chart={chart_version}, app={app_version})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chart-version", help="New chart version, e.g. 1.1190.2 or 1.1200.0-develop")
    parser.add_argument("--app-version", help="Override the derived app version, e.g. 1.19.0 or develop")
    parser.add_argument("--check", action="store_true", help="Verify README.md matches the current Chart.yaml; no --chart-version needed")
    args = parser.parse_args()

    if args.check:
        if args.chart_version or args.app_version:
            parser.error("--check does not take --chart-version/--app-version; it reads the committed Chart.yaml")
        return check()

    if not args.chart_version:
        parser.error("--chart-version is required unless --check is given")

    app_version = args.app_version or derive_app_version(args.chart_version)
    update_chart_yaml(args.chart_version, app_version)
    update_root_readme(args.chart_version, app_version)
    update_values_yaml(app_version)
    print(f"Set chart version={args.chart_version}, app version={app_version}, useImageTags={derive_use_image_tags(app_version)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
