# -- Define the estimated size of the Kasm deployment in expected session load.
#      small  = Up to 10-15 sessions
#      medium = Up to 25-30 sessions
#      large  = Up to 50+ sessions
deploymentSize: "small"

# -- Set the access URL to be used for the Kasm deployment.
# This is the value that should be used when generating a certificate and that this
# chart uses when the `certificate.certManager.enabled` is set to true.
publicAddr: ""

# -- Configure Ingress for your Kasm deployment. 
# 
ingress:
  enabled: true
  ingressClassName: ""
  annotations: {}
  labels: {}

# -- Configure the external-facing service type to use.
# Allowed service types: ClusterIP or LoadBalancer
#
# The service.annotations defined here only apply to the `proxy` service. If you wish to apply annotations
# to all services, use the annotations.service value at the bottom of this chart.
#
# NOTE: If ingress.enabled set to `true` service.type value MUST be set to `ClusterIP`.
#
service:
  type: ClusterIP
  annotations: {}

# Configure certificate settings.
# You can create your own certificate and upload it to the `secretName` supplied below, or if you have
# an existing cert-manager configured and you wish to use that, set the `secretName` and configure the
# associated cert-manager settings.
#
certificate:
  # -- Set the secret name where the certificate is stored
  # This secret name will store a certificate created by `cert-manager` if you set `cert-manager.enabled` to true
  #
  secretName: ""
  # For additional cert-manager configuration/deployment information refer to the online documentation
  # [Cert Manager Docs](https://cert-manager.io/v1.1-docs/installation/kubernetes/)
  # 
  # NOTE: If you do not enable `cert-manager`, you must generate your own certificates and add them to
  # Kubernetes
  #
  certManager:
    enabled: true
    # -- Setting addWildCard to true will automatically add *.<publicAddr> as a hostname served
    # by the Ingress, as well as adding it to the list of domains to generate a certificate for.
    addWildCard: true
    # -- Name of the Issuer/ClusterIssuer to use for certs
    # NOTE: You will always need to create this yourself when `certManager.enabled` is true.
    issuerName: "some-issuer"
    # -- Provide the kind of certificate to use, defaults to `Issuer` for security to scope the certificate to the
    # Kasm namespace.
    issuerKind: ""
    # -- Provide the group of Issuer that cert-manager should use, defaults to 'cert-manager.io' which is the
    # default Issuer group.
    issuerGroup: ""

# Kasm DB settings and configuration options
#
database:
  # -- Setting `initialize_db` to true assumes you want a newly initialized Kasm deployment. Setting this to false
  # is useful for deployment testing where you don't want to wait for DB initialization before using Kasm, or if
  # running Kasm upgrades.
  initialize_db: true
  # -- Configure the image repository where the image is stored. Use this to point to an private hosted
  # container registry instead of our public DockerHub hosted one.
  image:
    repository: kasmweb/postgres
    tag: 1.17.0
  storage:
    # -- Set the storage class to attach to the DB for storage.
    # NOTE: Leaving this blank will use the cluster-default storage class
    storageClassName: ""
    # -- Configure how the DB volume should be retained or deleted throughout the DB's lifecycle
    retentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  annotations: {}
  resources: {}
  labels: {}

# Kasm component resources and associated settings
#
components:
  # Configuration settings for the Kasm Nginx Proxy service
  proxy:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
    image:
      repository: kasmweb/proxy
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm API service
  api:
    image:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
      repository: kasmweb/api
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm Manager service
  manager:
    image:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
      repository: kasmweb/manager
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm Guac RDP service
  guac:
  # -- Configure the image repository where the image is stored. Use this to point to an private hosted
  # container registry instead of our public DockerHub hosted one.
    image:
      repository: kasmweb/kasm-guac
      tag: 1.17.0
    # -- Use this setting to enable/disable deployment of the Kasm Guacamole web RDP service
    # https://kasmweb.com/docs/latest/guide/connection_proxies.html#guacamole-guac
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm RDP Gateway service
  rdpGateway:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
    image:
      repository: kasmweb/rdp-gateway
      tag: 1.17.0
    # -- Use this setting to enable/disable deployment of the Kasm RDP Gateway service
    # https://kasmweb.com/docs/latest/guide/connection_proxies.html#rdp-gateway
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm RDP HTTPS Gateway service
  rdpHttpsGateway:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
    image:
      repository: kasmweb/rdp-https-gateway
      tag: 1.17.0
    # -- Use this setting to enable/disable deployment of the Kasm RDP HTTPS Gateway service.
    # This service allows users to use native RDP clients via HTTPS connections rather than exposing 3389.
    # https://kasmweb.com/docs/latest/guide/connection_proxies.html#rdp-https-gateway
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm Share service
  share:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
    image:
      repository: kasmweb/share
      tag: 1.17.0
    # -- Use this setting to enable/disable deployment of the Kasm Share and associated Redis services
    # https://kasmweb.com/docs/latest/guide/session_sharing.html
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  # Configuration settings for the Kasm Share Redis backend service
  redis:
    # -- Configure the image repository where the image is stored. Use this to point to an private hosted
    # container registry instead of our public DockerHub hosted one.
    image:
      repository: redis
      tag: 5-alpine
    annotations: {}
    resources: {}
    labels: {}

####################################
# Extra Kubernetes config settings #
####################################

# -- Configure global image pull policy
imagePullPolicy: "IfNotPresent"

# -- Use credentials for custom images or image repositories. Useful for offline or self-hosted repos, or dev builds.
imagePullSecrets: ""

# -- Create a dockerconfigjson secret as an image pull credential. Useful for offline or self-hosted repos, or dev builds.
imagePullCredentials: {}

# -- Cluster-wide Kubernetes DNS domain name
clusterDomain: "cluster.local"

# -- nodeSelector to apply for pod assignment
# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
nodeSelector: {}

# -- Apply Pod/Container security settings for Kasm resources
applySecurity: true

# -- Add Pod/Container healthchecks settings for Kasm resources
applyHealthChecks: true

# -- Configure global Pod restart policy for Kasm resources
restartPolicy: "Always"

# -- Custom labels to apply to all deployed resources
labels: {}

# Additional resource annotations to apply to resources created by this chart
annotations:
  # -- Additional certSecret annotations to apply to resources created by this chart
  certSecret: {}
  # -- Additional configMap annotations to apply to resources created by this chart
  configMap: {}
  # -- Additional deployment annotations to apply to resources created by this chart
  deployment: {}
  # -- Additional pod annotations to apply to resources created by this chart
  pod: {}
  # -- Additional service annotations to apply to resources created by this chart
  service: {}
  # -- Additional secret annotations to apply to resources created by this chart
  secret: {}
  # -- Additional ingress annotations to apply to resources created by this chart
  ingress: {}
  # -- Additional statefulSet annotations to apply to resources created by this chart
  statefulSet: {}

# Additional Kubernetes labels to apply to resources created by this chart
# See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ for more information
#
extraLabels:
  # -- Additional statefulSet labels to apply to resources created by this chart
  certSecret: {}
  # -- Additional configMap labels to apply to resources created by this chart
  configMap: {}
  # -- Additional deployment labels to apply to resources created by this chart
  deployment: {}
  # -- Additional pod labels to apply to resources created by this chart
  pod: {}
  # -- Additional secret labels to apply to resources created by this chart
  secret: {}
  # -- Additional service labels to apply to resources created by this chart
  service: {}
  # -- Additional ingress labels to apply to resources created by this chart
  ingress: {}
  # -- Additional job labels to apply to resources created by this chart
  job: {}
  # -- Additional jobPod labels to apply to resources created by this chart
  jobPod: {}
  # -- Additional statefulSet labels to apply to resources created by this chart
  statefulSet: {}
