deploymentSize: "small"
publicAddr: "kasm.contoso.com"

ingress:
  enabled: true
  ingressClassName: ""
  annotations:
    networking.gke.io/managed-certificates: "kasm-managed-cert"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
  labels: {}

route:
  enabled: false
  tls: {}
  annotations: {}
  labels: {}

# proxyService -- Configure the external-facing service type to use.
# Allowed service types: ClusterIP or LoadBalancer
#
# The service.annotations defined here only apply to the `proxy` service. If you wish to apply annotations
# to all services, use the annotations.service value at the bottom of this chart.
#
# NOTE: If ingress.enabled or route.enabled set to `true` service.type MUST be set to `ClusterIP`.
#
proxyService:
  type: ClusterIP
  annotations:
    cloud.google.com/backend-config: '{"default": "kasm-proxy-backend-config"}'
  labels: {}

certificate:
  secretName: ""
  certManager:
    enabled: false
    addWildCard: true
    issuerName: cert-issuer-name
    issuerKind: cert-issuer-kind
    issuerGroup: ""

database:
  standalone: false
  hostname: kasm-db
  port: 5432
  kasmDbName: kasm
  kasmDbUser: kasmapp
  postgresMasterUser: {}
  initialize_db: true
  image:
    repository: kasmweb/postgres
    tag: 1.17.0
  storage:
    # database.storage.storageClassName -- Select a storage class here suitable to your deployment requierments. Something
    # shared across your workers, such as an NFS backend would be useful to allow the DB to migrate to handle Node maintenance
    #
    storageClassName: storage-class-name
    retentionPolicy:
      whenDeleted: Delete
      whenScaled: Retain
  annotations: {}
  resources: {}
  labels: {}

components:
  proxy:
    image:
      repository: kasmweb/proxy
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  api:
    image:
      repository: kasmweb/api
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  manager:
    image:
      repository: kasmweb/manager
      tag: 1.17.0
    annotations: {}
    resources: {}
    labels: {}
  guac:
    image:
      repository: kasmweb/kasm-guac
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpGateway:
    image:
      repository: kasmweb/rdp-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  rdpHttpsGateway:
    image:
      repository: kasmweb/rdp-https-gateway
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  share:
    image:
      repository: kasmweb/share
      tag: 1.17.0
    enabled: true
    annotations: {}
    resources: {}
    labels: {}
  redis:
    image:
      repository: redis
      tag: 5-alpine
    annotations: {}
    resources: {}
    labels: {}

imagePullPolicy: "IfNotPresent"
imagePullSecrets: ""
imagePullCredentials: {}
clusterDomain: "cluster.local"
affinity: {}
applySecurity: true
applyHealthChecks: true
restartPolicy: "Always"
labels: {}

# nodeSelector -- Configure node selector settings for your Kasm pods - 
# [Kubernetes Node Selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector).
#
nodeSelector:
  node-selector: prod

annotations:
  certSecret: {}
  configMap: {}
  deployment: {}
  pod: {}
  service: {}
  secret: {}
  statefulSet: {}

extraLabels:
  certSecret: {}
  configMap: {}
  deployment: {}
  pod: {}
  secret: {}
  service: {}
  job: {}
  jobPod: {}
  statefulSet: {}

# extraObjects -- Deploy additional Kubernetes manifests
extraObjects:
  - apiVersion: cloud.google.com/v1
    kind: BackendConfig
    metadata:
      name: kasm-proxy-backend-config
    spec:
      timeoutSec: 28800
      connectionDraining:
        drainingTimeoutSec: 60
      healthCheck:
        checkIntervalSec: 15
        healthyThreshold: 2
        unhealthThreshold: 3
        timeoutSec: 10
        port: 8443
        type: HTTPS
        requestPath: /api/__healthcheck
  - apiVersion: networking.gke.io/v1beta1
    kind: FrontendConfig
    metadata:
      name: kasm-frontend-config
    spec:
      redirectToHttps:
        enabled: true
  - apiVersion: networking.gke.io/v1
    kind: ManagedCertificate
    metadata:
      name: kasm-managed-cert
    spec:
      domains:
        - kasm.contoso.com