apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.components.api.name }}-deployment
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.components.api.name }}
    app.kubernetes.io/component: api
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.components.api.replicas | default (include "replicas.preset" (dict "node" "api" "size" .Values.deploymentSize)) }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 (.Values.components.api.replicas | default (include "replicas.preset" (dict "node" "api" "size" .Values.deploymentSize))) }}
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ .Values.components.api.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.components.api.name }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
    spec:
      restartPolicy: {{ .Values.global.image.restartPolicy }}
      {{- if .Values.global.image.pullSecrets }}
        {{- include "image.pullSecrets" . | indent 6 }}
      {{- end }}
      {{- if .Values.kasmApp.applyHardening }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      initContainers:
        - name: db-is-ready
          image: "{{ .Values.components.api.image }}:{{ .Values.components.api.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: db-password
          command:
            - /bin/bash
            - -c
          args:
            - |
              while [ ! $(PGPASSWORD=$POSTGRES_PASSWORD psql -U kasmapp -d kasm -h db -t -c "select zone_id from zones" 2>/dev/null | wc -l) -ge 2 ]; do echo "Waiting for DB to initialize..."; sleep 5; done
          {{- if .Values.kasmApp.applyHardening }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
      containers:
        - name: {{ .Values.components.api.name }}-container
          image: "{{ .Values.components.api.image }}:{{ .Values.components.api.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: START_SERVICES
              value: "true"
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: db-password
          ports:
            - name: {{ .Values.components.api.name }}-pt
              containerPort: 8080
              protocol: TCP
          {{- if .Values.components.api.addHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "portName" (printf "%s-pt" .Values.components.api.name) ) | indent 12 }}
          {{- end }}
          {{- if .Values.components.api.addHealthChecks }}
          readinessProbe:
            {{- include "health.http" (dict "path" "/api/__healthcheck" "portName" (printf "%s-pt" .Values.components.api.name) ) | indent 12 }}
          {{- end }}
          {{- if .Values.components.api.resources }}
          resources: {{- toYaml .Values.components.api.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" "api" "size" .Values.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- if .Values.applyPodSecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
