{{/*
Deploy the Certificates with certManager
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.certificate.certManager.enabled true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $constants.proxy.name }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.proxy.name }}-cert
    app.kubernetes.io/component: certificate
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  {{- if or .Values.annotations.certSecret .Values.extraLabels.certSecret }}
  secretTemplate:
  {{- with .Values.annotations.certSecret }}
    annotations: {{ toYaml . | indent 6 }}
  {{- end }}
  {{- with .Values.extraLabels.certSecret }}
    labels: {{ toYaml . | indent 6 }}
  {{- end }}
  {{- end }}
  secretName: {{ .Values.certificate.secretName }}
  commonName: {{ .Values.publicAddr | quote }}
  dnsNames:
    - {{ .Values.publicAddr | quote }}
    {{- if .Values.certificate.certManager.addWildCard }}
    - {{ printf "*.%s" .Values.publicAddr | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.certManager.issuerName }}
    kind: {{ .Values.certificate.certManager.issuerKind | default "Issuer" }}
    group: {{ .Values.certificate.certManager.issuerGroup | default "cert-manager.io" }}
{{- end }}