{{/*
Deploy the Certificates with cert-manager
*/}}
{{- if eq .Values.certificate.cert-manager.enabled true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cert
    app.kubernetes.io/component: certificate
    {{- include "kasm.defaultLabels" $values | indent 4 }}
spec:
  {{- if or .Values.annotations.certSecret .Values.extraLabels.certSecret }}
  secretTemplate:
  {{- with .Values.annotations.certSecret }}
    annotations: {{ toYaml . | indent 6 }}
  {{- end }}
  {{- with .Values.extraLabels.certSecret }}
    labels: {{ toYaml . | indent 6 }}
  {{- end }}
  {{- end }}
  secretName: {{ .Values.certificate.secretName }}
  commonName: {{ quote .Values.publicAddr }}
  dnsNames:
    - {{ quote .Values.publicAddr }}
    {{- if .Values.certificate.cert-manager.addWildCard }}
    - {{ printf "*.%s" .Values.publicAddr }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.cert-manager.issuerName }}
    kind: {{ .Values.certificate.cert-manager.issuerKind | default "Issuer" }}
    group: {{ .Values.certificate.cert-manager.issuerGroup | default "cert-manager.io" }}
{{- end }}