{{/*
Initialize the DB
*/}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-init-job
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db-init
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-db-init
        app.kubernetes.io/component: db-init
        {{- include "kasm.defaultLabels" . | indent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
        - name: db-is-ready
          image: {{ $values.api.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while ! pg_isready -h db -p {{ $values.db.port }} -t 10; do echo "Waiting for DB..."; sleep 5; done
      containers:
        - name: {{ .Release.Name }}-db-init-container
          image: {{ $values.api.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: POST_DB_INIT_EXIT
              value: "true"
            - name: DB_AUTO_INITIALIZE
              value: {{ .Values.database.initialize_db | quote }}
            - name: DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: admin-password
            - name: DEFAULT_MANAGER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: manager-token
            - name: DEFAULT_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: service-token
            - name: DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: user-password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              if [[ "$DB_AUTO_INITIALIZE" == "true" ]]; then /usr/bin/startup.sh; else echo "DB already initialized."; fi
