{{/*
Deploy the Guac if .Values.components.guac.enabled set to true
*/}}
{{- $guacSvcName  := "kasm-guac" -}}
{{- $guacSvcPort := 3000 -}}
{{- $guacConnectPorts := (list "3001" "3002" "3003" "3004") -}}
{{- if eq .Values.components.guac.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $guacSvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $guacSvcName }}-svc
    app.kubernetes.io/component: {{ $guacComponent }}
    {{- include "kasm.defaultLabels" $values | indent 4 }}
  {{- if or .Values.components.guac.labels .Values.extraLabels.service .Value.labels }}
    {{- with .Values.components.guac.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.service }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with .Values.annotations.service }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $guacName }}
  ports:
    - name: {{ printf "%s-svc-%s" $guacSvcName $guacSvcPort }}
      protocol: TCP
      port: {{ $guacSvcPort }}
    {{- range $guacConnectPorts }}
    - name: {{ printf "%s-svc-%s" $guacSvcName . }}
      protocol: TCP
      port: {{ . }}
    {{- end }}
{{- end }}