{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kasm-ingress
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kasm-ingress
{{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  tls:
  - hosts:
      - {{ .Values.hostname | quote }}
      {{- if gt (len .Values.altHostnames) 0 }}
        {{- range .Values.altHostnames }}
      - {{ . | quote }}
      {{- end }}
      {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kasm-proxy
            port:
              number: 8080
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: kasm-api
            port:
              number: 8080
{{- if .Values.components.share.deploy }}
      - path: /api/share/
        pathType: Prefix
        backend:
          service:
            name: kasm-share
            port:
              number: 8182
{{- end }}
{{- end }}