{{/*
Deploy the Kasm ingress if .Values.ingress.enabled set to true
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ingress
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or .Values.ingress.labels .Values.extraLabels.ingress .Values.labels }}
    {{- with .Values.ingress.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.ingress }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with .Values.annotations.ingress }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  tls:
    - hosts:
        - {{ .Values.publicAddr | quote }}
        {{- if eq .Values.certificate.certManager.addWildCard true }}
        - {{ printf "*.%s" $.Values.publicAddr | quote }}
        {{- end }}
      secretName: {{ .Values.certificate.secretName }}
  rules:
  - host: {{ .Values.publicAddr | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $constants.proxy.svc }}
              port:
                number: {{ $constants.proxy.http }}
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: {{ $constants.api.svc }}
              port:
                number: {{ $constants.api.port }}
{{- if eq .Values.components.share.deploy true }}
        - path: /api/share/
          pathType: Prefix
          backend:
            service:
              name: {{ $constants.share.svc }}
              port:
                number: {{ $constants.share.port }}
{{- end }}
{{- end }}