{{/*
Generate Kasm passwords and upload as secrets. IF a secret currently exists in the namespace with the same name,
this will prefer that and not create new ones. If you want/need new Kasm passwords, delete the current secret
from Kubernetes to create a new one.
*/}}
{{- $namespace := .Release.Namespace | quote }}
{{- $secretName := (printf "%s-passwords" .Release.Name) }}
{{- $secretsObj := (lookup "v1" "Secret" $namespace $secretName) | default dict }}
{{- $secretsData := (get $secretsObj "data") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $secretName }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- if or .Values.extraLabels.secret .Values.labels }}
      {{- with .Values.extraLabels.secret }}{{- toYaml . | indent 4 }}{{- end }}
      {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- end }}
  annotations:
    helm.sh/hook: pre-install,post-delete
    {{- if .Values.annotations.secret }}
      {{- with .Values.annotations.secret }}{{- toYaml . | indent 4 }}{{- end }}
    {{- end }}
type: Opaque
data:
{{- range (list "managerToken" "serviceToken" "dbPassword" "redisPassword" "adminPassword" "userPassword") }}
  {{- $valueSecret := (get $secretsData (kebabcase .)) | default (randAlphaNum 26 | b64enc) }}
  {{- if or (and (eq "redis-password" .) (eq $.Values.components.share.enabled true)) (ne "redis-password" .) }}
  {{ kebabcase . }}: {{ $valueSecret | quote }}
  {{- end }}
{{- end }}