{{/*
Generate Kasm passwords and upload as secrets
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: kasm-passwords
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kasm-passwords
    {{- include "kasm.defaultLabels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install,post-delete
type: Opaque
data:
{{- $namespace := .Values.global.namespace | default .Release.Namespace | quote }}
{{- $secretName := (printf "%s%s" "kasm-passwords") | quote }}
{{- $secretsObj := (lookup "v1" "Secret" $namespace $secretName) | default dict }}
{{- $secretsData := (get $secretsObj "data") | default dict }}
{{- range $key, $value := .Values.passwords }}
  {{- $valueSecret := (get $secretsData (kebabcase $key)) | default (randAlphaNum 26 | b64enc) ($value | b64enc) }}
  {{- if or (and (eq "redis" $key) (eq $.Values.kasmApp.servicesToDeploy.kasmShare.deploy true)) (ne "redis" $key) }}
  {{ kebabcase $key }}: {{ $valueSecret | quote }}
  {{- end }}
{{- end }}