{{/*
Kasm Manager server Deployment definition
*/}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
{{- $managerReplicas := include "replicas.preset" (dict "node" $values.manager.component "size" .Values.deploymentSize) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $values.manager.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.manager.name }}
    app.kubernetes.io/component: {{ $values.manager.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or .Values.components.manager.labels .Values.extraLabels.deployment .Values.labels }}
    {{- with .Values.components.manager.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- if or .Values.components.manager.annotations .Values.annotations.deployment }}
  annotations:
    {{- with .Values.annotations.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.components.manager.annotations }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
spec:
  replicas: {{ $managerReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 $managerReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $values.manager.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $values.manager.name }}
        app.kubernetes.io/component: {{ $values.manager.component }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
      {{- if or .Values.components.manager.labels .Values.extraLabels.pod .Values.labels }}
        {{- with .Values.components.manager.labels }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with .Values.extraLabels.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
      {{- end }}
      {{- if or .Values.components.manager.annotations .Values.annotations.pod }}
      annotations:
        {{- with .Values.annotations.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with .Values.components.manager.annotations }}{{- toYaml . | indent 8 }}{{- end }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.applySecurity }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      initContainers:
        {{- include "kasm.initContainer" (dict "serviceName" $values.api.svc "servicePort" $values.api.port "path" "/api/__healthcheck" "schema" "http" "image" $values.api.image) | nindent 8 }}
        {{- if .Values.applySecurity }}
          {{- include "kasm.containerSecurity" . | indent 10 }}
        {{- end }}
      containers:
        - name: {{ $values.manager.name }}-container
          image: {{ $values.manager.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
          ports:
            - name: {{ $values.manager.name }}-pt
              containerPort: {{ $values.manager.port }}
              protocol: TCP
          {{- if .Values.addHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "portName" (printf "%s-pt" $values.manager.name) ) | indent 12 }}
          {{- end }}
          {{- if .Values.addHealthChecks }}
          readinessProbe:
            {{- include "health.http" (dict "path" "/__healthcheck" "portName" (printf "%s-pt" $values.manager.name) ) | indent 12 }}
          {{- end }}
          {{- if .Values.components.manager.resources }}
          resources: {{- toYaml .Values.components.manager.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" $values.manager.component "size" .Values.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- if .Values.applyHardening }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
          volumeMounts:
            - name: {{ $values.manager.name }}-tmp
              mountPath: /tmp
      volumes:
        - name: {{ $values.manager.name }}-tmp
          emptyDir:
            sizeLimit: 1Gi