{{/*
Deploy the Manager .Values.components.manager
*/}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.manager.svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.manager.svc }}-svc
    app.kubernetes.io/component: {{ $values.manager.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or .Values.components.manager.labels .Values.extraLabels.service .Values.labels }}
    {{- with .Values.components.manager.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.service }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with .Values.annotations.service }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $values.manager.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $values.manager.svc ($values.manager.port | toString) }}
      protocol: TCP
      port: {{ $values.manager.port }}