{{/*
Kasm Proxy server Deployment definition
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- $proxyReplicas := include "replicas.preset" (dict "node" $constants.proxy.component "size" .Values.deploymentSize) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $constants.proxy.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.proxy.name }}
    app.kubernetes.io/component: {{ $constants.proxy.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or .Values.components.proxy.labels .Values.extraLabels.deployment .Values.labels }}
    {{- with .Values.components.proxy.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- if or .Values.components.proxy.annotations .Values.annotations.deployment }}
  annotations:
    {{- with .Values.annotations.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.components.proxy.annotations }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
spec:
  replicas: {{ $proxyReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 $proxyReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $constants.proxy.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $constants.proxy.name }}
        app.kubernetes.io/component: {{ $constants.proxy.component }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
      {{- if or .Values.components.proxy.labels .Values.extraLabels.pod .Values.labels }}
        {{- with .Values.components.proxy.labels }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with .Values.extraLabels.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
      {{- end }}
      {{- if or .Values.components.proxy.annotations .Values.annotations.pod }}
      annotations:
        {{- with .Values.annotations.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with .Values.components.proxy.annotations }}{{- toYaml . | indent 8 }}{{- end }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.applySecurity }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      initContainers:
        {{- if .Values.applySecurity }}
        - name: {{ $constants.proxy.name }}-data-perms
          image: {{ $constants.api.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
          args:
            - |
              echo "Setting permissions and ownership for /var/cache/nginx..." && chown -R 1000:1000 /var/cache/nginx && chmod -R 755 /var/cache/nginx
              echo "Setting permissions and ownership for /var/log/external/nginx..." && chown -R 1000:1000 /var/log/external/nginx && chmod -R 755 /var/log/external/nginx
              echo "Setting permissions and ownership for /tmp..." && chmod -R 777 /tmp
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: {{ $constants.proxy.name }}-data
              mountPath: /var/cache/nginx
            - name: {{ $constants.proxy.name }}-data
              mountPath: /var/log/external/nginx
            - name: {{ $constants.proxy.name }}-data
              mountPath: /run
        {{- end }}
        {{- include "kasm.initContainer" (dict "serviceName" $constants.api.svc "servicePort" $constants.api.port "path" "/api/__healthcheck" "schema" "http" "image" $constants.api.image) | nindent 8 }}
        {{- if .Values.applySecurity }}
          {{- include "kasm.containerSecurity" . | indent 10 }}
        {{- end }}
        {{- include "kasm.initContainer" (dict "serviceName" $constants.manager.svc "servicePort" $constants.manager.port "path" "/__healthcheck" "schema" "http" "image" $constants.api.image) | nindent 8 }}
        {{- if .Values.applySecurity }}
          {{- include "kasm.containerSecurity" . | indent 10 }}
        {{- end }}
        {{- if .Values.components.share.enabled }}
          {{- include "kasm.initContainer" (dict "serviceName" $constants.share.svc "servicePort" $constants.share.port "path" "/__healthcheck" "schema" "http" "image" $constants.api.image) | nindent 8 }}
          {{- if .Values.applySecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
        {{- end }}
        {{- if .Values.components.guac.enabled }}
          {{- include "kasm.initContainer" (dict "serviceName" $constants.guac.svc "servicePort" $constants.guac.port "path" "/__healthcheck" "schema" "http" "image" $constants.api.image) | nindent 8 }}
          {{- if .Values.applySecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
        {{- end }}
        {{- if .Values.components.rdpGateway.enabled }}
          {{- include "kasm.initContainer" (dict "serviceName" $constants.rdpGateway.svc "servicePort" $constants.rdpGateway.port "path" "/__healthcheck" "schema" "http" "image" $constants.api.image) | nindent 8 }}
          {{- if .Values.applySecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
        {{- end }}
      containers:
        - name: {{ $constants.proxy.name }}-container
          image: {{ $constants.proxy.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.components.proxy.resources }}
          resources: {{- toYaml .Values.components.proxy.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" $constants.proxy.component "size" .Values.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- if .Values.applySecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
          volumeMounts:
            - name: {{ $constants.proxy.name }}-cert
              mountPath: /etc/ssl/certs/kasm_nginx.crt
              subPath: tls.crt
            - name: {{ $constants.proxy.name }}-cert
              mountPath: /etc/ssl/private/kasm_nginx.key
              subPath: tls.key
            - name: {{ $constants.proxy.name }}-settings-config
              mountPath: /etc/nginx/conf.d
            - name: {{ $constants.proxy.name }}-services-config
              mountPath: /etc/nginx/conf.d/services.d
            - name: {{ $constants.proxy.name }}-base-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.applySecurity }}
            - name: {{ $constants.proxy.name }}-data
              mountPath: /var/cache/nginx
            - name: {{ $constants.proxy.name }}-data
              mountPath: /var/log/external/nginx
            - name: {{ $constants.proxy.name }}-data
              mountPath: /run
            {{- end }}
          ports:
            - name: {{ $constants.proxy.portName }}-http
              containerPort: {{ $constants.proxy.http }}
              protocol: TCP
            - name: {{ $constants.proxy.portName }}-https
              containerPort: {{ $constants.proxy.https }}
              protocol: TCP
          {{- if .Values.applyHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "portName" $constants.proxy.portName ) | indent 12 }}
          {{- end }}
          {{- if .Values.applyHealthChecks }}
          readinessProbe:
            {{- include "health.command" (dict "command" "nginx -t") | indent 12 }}
          {{- end }}
      volumes:
        - name: {{ $constants.proxy.name }}-cert
          secret:
            secretName: {{ .Values.certificate.secretName }}
        - name: {{ $constants.proxy.name }}-base-config
          configMap:
            name: {{ $constants.proxy.name }}-base-configmap
        - name: {{ $constants.proxy.name }}-settings-config
          configMap:
            name: {{ $constants.proxy.name }}-settings-configmap
        - name: {{ $constants.proxy.name }}-services-config
          configMap:
            name: {{ $constants.proxy.name }}-services-configmap
        {{- if .Values.applySecurity }}
        - name: {{ $constants.proxy.name }}-data
          emptyDir:
            sizeLimit: 1Gi
        {{- end }}
