{{/*
Deploy the Kasm Proxy service
*/}}
{{- if and .Values.ingress.enabled (eq .Values.service.type "LoadBalancer") -}}
  {{- fail "The service.type must not be LoadBalancer when using an ingress - any load balancer should be provisioned by your ingress controller. Set service.type=ClusterIP instead" -}}
{{- end -}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
{{- $proxyHttpsPort := 8443 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.proxy.svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.proxy.svc }}-svc
    app.kubernetes.io/component: {{ $values.proxy.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or .Values.components.proxy.labels .Values.extraLabels.service .Values.labels }}
    {{- with .Values.components.proxy.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.service }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- if or .Values.annotations.service .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.annotations.service | indent 4 }}
    {{- toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ default "ClusterIp" .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ $values.proxy.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $values.proxy.svc ($values.proxy.http | toString) }}
      protocol: TCP
      port: {{ $values.proxy.http }}
    - name: {{ printf "%s-svc-%s" $values.proxy.svc ($values.proxy.https | toString) }}
      protocol: TCP
      port: {{ $values.proxy.https }}
