{{/*
Deploy the RDP HTTPS Gateway if .Values.kasmApp.servicesToDeploy.rdpHttpsGateway.deploy set to true
*/}}
{{- $rdpHttpsGatewayComponent := "rdp-https-gateway" -}}
{{- $rdpHttpsGatewayName := (printf "%s-%s" .Release.Name $rdpHttpsGatewayComponent) -}}
{{- $rdpHttpsGatewayImage := (printf "%s:%s" .Values.components.rdpHttpsGateway.image.repository .Values.components.rdpHttpsGateway.image.tag) -}}
{{- $rdpHttpsGatewayReplicas := include "replicas.preset" (dict "node" $rdpHttpsGatewayComponent "size" .Values.deploymentSize) -}}
{{- if eq .Values.components.rdpHttpsGateway.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $rdpHttpsGatewayName }}-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $rdpHttpsGatewayName }}
    app.kubernetes.io/component: {{ $rdpHttpsGatewayComponent }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or $.Values.components.rdpHttpsGateway.labels $.Values.extraLabels.deployment $.Value.labels }}
    {{- with $.Values.components.rdpHttpsGateway.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.extraLabels.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- if or $.Values.components.rdpHttpsGateway.annotations .Values.annotations.deployment }}
  annotations:
    {{- with $.Values.annotations.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.components.rdpHttpsGateway.annotations }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
spec:
  replicas: {{ $rdpHttpsGatewayReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 $apiReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $rdpHttpsGatewayName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $rdpHttpsGatewayName }}
        app.kubernetes.io/component: {{ $rdpHttpsGatewayComponent }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
      {{- if or $.Values.components.rdpHttpsGateway.labels $.Values.extraLabels.pod $.Value.labels }}
        {{- with $.Values.components.rdpHttpsGateway.labels }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with $.Values.extraLabels.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
      {{- end }}
      {{- if or $.Values.components.rdpHttpsGateway.annotations $.Values.annotations.pod }}
      annotations:
        {{- with $.Values.annotations.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with $.Values.components.rdpHttpsGateway.annotations }}{{- toYaml . | indent 8 }}{{- end }}
      {{- end }}
    spec:
      restartPolicy: {{ $.Values.restartPolicy }}
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      {{- end }}
      {{- if $.Values.applySecurity }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      initContainers:
        {{- include "kasm.initContainer" (dict "serviceName" $apiSvcName "servicePort" $apiSvcPort "path" "/api/__healthcheck" "schema" "http") | nindent 8 }}
        {{- if $.Values.applySecurity }}
        - name: {{ $rdpHttpsGatewayName }}-tmp-perms
          image: {{ $apiImage }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
          args:
            - |
              echo "No customizations needed yet."
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: {{ $rdpHttpsGatewayName }}-data
              mountPath: /opt/kasm/current/log
            - name: {{ $rdpHttpsGatewayName }}-data
              mountPath: /tmp
        {{- end }}
      containers:
        - name: {{ $rdpHttpsGatewayName }}-container
          image: {{ $rdpHttpsGatewayImage }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          env:
            - name: SERVER_ZONE_NAME
              value: "default"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: service-token
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
          ports:
            - name: {{ $rdpHttpsGatewayName }}-pt
              containerPort: {{ $rdpHttpsGatewaySvcPort }}
              protocol: TCP
          {{- if $.Values.addHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "portName" (printf "%s-pt" $rdpHttpsGatewayName) ) | indent 12 }}
          {{- end }}
          {{- if $.Values.addHealthChecks }}
          readinessProbe:
            {{- include "health.https" (dict "path" "/rdp-https-gateway/__healthcheck" "portName" (printf "%s-pt" $rdpHttpsGatewayName) ) | indent 12 }}
          {{- end }}
          {{- if $.Values.components.rdpHttpsGateway.resources }}
          resources: {{- toYaml $.Values.components.rdpHttpsGateway.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" "rdp" "size" $.Values.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- if $.Values.applySecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
          volumeMounts:
            - name: {{ $rdpHttpsGatewayName }}-cert
              mountPath: /opt/rdpgw/server.pem
              subPath: tls.crt
            - name: {{ $rdpHttpsGatewayName }}-cert
              mountPath: /opt/rdpgw/key.pem
              subPath: tls.key
            - name: {{ $rdpHttpsGatewayName }}-data
              mountPath: /opt/kasm/current/log
            - name: {{ $rdpHttpsGatewayName }}-data
              mountPath: /tmp
      volumes:
        - name: {{ $rdpHttpsGatewayName }}-cert
          secret:
            secretName: {{ $.Values.certificate.secretName }}
        - name: {{ $rdpHttpsGatewayName }}-data
          emptyDir:
            sizeLimit: 150Mi
{{- end }}