{{/*
Deploy the Redis if .Values.components.rdpHttpsGateway.enabled set to true
*/}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.components.rdpHttpsGateway.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.rdpHttpsGateway.svc }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.rdpHttpsGateway.svc }}-svc
    app.kubernetes.io/component: {{ $values.rdpHttpsGateway.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or $.Values.components.rdpHttpsGateway.labels $.Values.extraLabels.service $.Values.labels }}
    {{- with $.Values.components.rdpHttpsGateway.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.extraLabels.service }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with $.Values.annotations.service }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $values.rdpHttpsGateway.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $values.rdpHttpsGateway.svc ($values.rdpHttpsGateway.port | toString) }}
      protocol: TCP
      port: {{ $values.rdpHttpsGateway.port }}
{{- end }}