{{/*
Deploy the Redis if .Values.components.rdpHttpsGateway.enabled set to true
*/}}
{{- if .Values.components.rdpHttpsGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.components.rdpHttpsGateway.name }}
  namespace: {{ $values.Values.namespace | default $values.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.components.rdpHttpsGateway.name }}-svc
    {{- include "kasm.defaultLabels" $values | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.components.rdpHttpsGateway.name }}
  ports:
    - name: {{ .Values.components.rdpHttpsGateway.name }}-svc-9443
      protocol: TCP
      port: 9443
{{- end }}