{{/*
Deploy the Redis if .Values.components.share.enabled set to true
*/}}
{{- if .Values.components.share.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.components.redis.name }}
  namespace: {{ $values.Values.namespace | default $values.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.components.redis.name }}-svc
    {{- include "kasm.defaultLabels" $values | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.components.redis.name }}
  ports:
    - name: {{ .Values.components.redis.name }}-svc-6379
      protocol: TCP
      port: 6379
{{- end }}