{{/*
Deploy the Redis if .Values.kasmApp.servicesToDeploy.share.deploy set to true
*/}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
{{- $redisReplicas := include "replicas.preset" (dict "node" $values.redis.component "size" .Values.deploymentSize) -}}
{{- if eq .Values.components.share.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $values.redis.name }}-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.redis.name }}
    app.kubernetes.io/component: {{ $values.redis.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or $.Values.components.redis.labels $.Values.extraLabels.deployment $.Values.labels }}
    {{- with $.Values.components.redis.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.extraLabels.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- if or $.Values.components.redis.annotations $.Values.annotations.deployment }}
  annotations:
    {{- with $.Values.annotations.deployment }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.components.redis.annotations }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $values.redis.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $values.redis.name }}
        app.kubernetes.io/component: {{ $values.redis.component }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
      {{- if or $.Values.components.redis.labels $.Values.extraLabels.pod $.Values.labels }}
        {{- with $.Values.components.redis.labels }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with $.Values.extraLabels.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
      {{- end }}
      {{- if or $.Values.components.redis.annotations $.Values.annotations.pod }}
      annotations:
        {{- with $.Values.annotations.pod }}{{- toYaml . | indent 8 }}{{- end }}
        {{- with $.Values.components.redis.annotations }}{{- toYaml . | indent 8 }}{{- end }}
      {{- end }}
    spec:
      restartPolicy: {{ $.Values.restartPolicy }}
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      {{- end }}
      {{- if $.Values.applySecurity }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      containers:
        - name: {{ $values.redis.name }}-container
          image: {{ $values.redis.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-secrets
                  key: redis-password
          {{- if $.Values.components.redis.resources }}
          resources: {{- toYaml $.Values.components.redis.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" $values.redis.component "size" $.Values.deploymentSize) | nindent 12 }}
          {{- end }}
          command:
            - redis-server
          args: 
            - --requirepass $(REDIS_PASSWORD)
          ports:
            - name: {{ $values.redis.name }}-pt
              containerPort: {{ $values.redis.port }}
              protocol: TCP
          {{- if $.Values.addHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "portName" (printf "%s-pt" $values.redis.name) ) | indent 12 }}
          readinessProbe:
            {{- include "health.command" (dict "command" (printf "redis-cli -p %s -a $REDIS_PASSWORD ping 2>/dev/null | grep -q PONG" $values.redis.port)) | indent 12 }}
          {{- end }}
          {{- if $.Values.applySecurity }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
{{- end }}