{{/*
Deploy the Kasm OpenShift Route if .Values.route.enabled set to true
*/}}
{{- if and .Values.ingress.enabled .Values.route.enabled -}}
  {{- fail "The ingress.enabled and route.enabled cannot both be set. Either set ingress.enabled=false or route.enabled=false." -}}
{{- end -}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.route.enabled true }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-route
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or .Values.route.labels .Values.extraLabels.route .Values.labels }}
    {{- with .Values.route.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.extraLabels.route }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with .Values.annotations.route }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  host: {{ .Values.publicAddr | quote }}
  to:
    kind: Service
    name: {{ $constants.proxy.svc }}
    weight: 100
  port:
    targetPort: {{ $constants.proxy.https }}
  tls:
    {{- /* Default to edge termination, configurable by value */}}
    termination: {{ .Values.route.tls.termination | default "edge" }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if .Values.route.tls.certificate }}
    certificate: |
      {{- .Values.route.tls.certificate | nindent 6 }}
    {{- end }}
    {{- if .Values.route.tls.key }}
    key: |
      {{- .Values.route.tls.key | nindent 6 }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: |
      {{- .Values.route.tls.caCertificate | nindent 6 }}
    {{- end }}
    {{- if .Values.route.tls.destinationCACertificate }}
    destinationCACertificate: |
      {{- .Values.route.tls.destinationCACertificate | nindent 6 }}
    {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy | default "None" }}
{{- end }}
