{{/*
Deploy the Share if .Values.components.share.enabled set to true
*/}}
{{- $shareSvcName  := "kasm-share" -}}
{{- $shareSvcPort := 8182 -}}
{{- if eq .Values.components.share.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $shareSvcName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $shareSvcName }}-svc
    app.kubernetes.io/component: {{ $shareComponent }}
    {{- include "kasm.defaultLabels" $values | indent 4 }}
  {{- if or $.Values.components.share.labels $.Values.extraLabels.service $.Value.labels }}
    {{- with $.Values.components.share.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.extraLabels.service }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with $.Values.annotations.service }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $shareName }}
  ports:
    - name: {{ printf "%s-svc-%s" $shareSvcName $shareSvcPort }}
      protocol: TCP
      port: {{ $shareSvcPort }}
{{- end }}