{{/*
Deploy the Share if .Values.components.share.enabled set to true
*/}}
{{- if .Values.components.share.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.components.share.name }}
  namespace: {{ $values.Values.namespace | default $values.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.components.share.name }}-svc
    {{- include "kasm.defaultLabels" $values | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.components.share.name }}
  ports:
    - name: {{ .Values.components.share.name }}-svc-8182
      protocol: TCP
      port: 8182
{{- end }}