{{/*
Deploy the Share if .Values.components.share.enabled set to true
*/}}
{{- $values := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.components.share.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.share.svc }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.share.svc }}-svc
    app.kubernetes.io/component: {{ $values.share.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  {{- if or $.Values.components.share.labels $.Values.extraLabels.service $.Values.labels }}
    {{- with $.Values.components.share.labels }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.extraLabels.service }}{{- toYaml . | indent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | indent 4 }}{{- end }}
  {{- end }}
  {{- with $.Values.annotations.service }}
  annotations: {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $values.share.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $values.share.svc ($values.share.port | toString) }}
      protocol: TCP
      port: {{ $values.share.port }}
{{- end }}