---
apiVersion: batch/v1
kind: Job
metadata:
  name: upload
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
      restartPolicy: OnFailure
      initContainers:
        - name: kasm-old-db-upload-set-perms
          image: kasmweb/api:1.18.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
          args:
            - |
              echo "Setting permissions and ownership for /data/kasm-db-dump..."
              chown -R 1000:1000 /data/kasm-db-dump
              chmod -R 755 /data/kasm-db-dump
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: kasm-db-dump
              mountPath: /data/kasm-db-dump
      containers:
        - name: kasm-old-db-upload-container
          image: kasmweb/api:1.18.0
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while [[ ! -f /data/kasm-db-dump/kasm_dump.tar ]]; do sleep 5; echo "Waiting for DB file upload..."; done
              echo "File uploading."
              
              FILE="/data/kasm-db-dump/kasm_dump.tar"
              while true; do
                SIZE1=$(stat -c%s "$FILE" 2>/dev/null || echo 0)
                sleep 5
                SIZE2=$(stat -c%s "$FILE" 2>/dev/null || echo 0)
                if [ "$SIZE1" -gt 0 ] && [ "$SIZE1" -eq "$SIZE2" ]; then
                  echo "✅ File upload complete. Final size: $SIZE1 bytes"
                  break
                else
                  echo "⏳ Upload in progress... (size: $SIZE2 bytes)"
                fi
              done
          volumeMounts:
            - name: kasm-db-dump
              mountPath: /data/kasm-db-dump
              readOnly: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: kasm-db-dump
          persistentVolumeClaim:
            claimName: kasm-db-dump-pvc
---
# PVC definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-db-dump-pvc
spec:
  # storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
