---
apiVersion: v1
kind: Secret
metadata:
  name: kasm-secrets
  namespace: kasm-namespace
type: Opaque
data:
  manager-token: "base64 encoded kasm manager token"
  service-token: "base64 encoded kasm service token"
  db-password: "base64 encoded kasm db password"
  # Optional values - is very useful to have to ensure consistency across deployments
  # as the new helm chart will create a secret called "release-name-secrets" and will
  # automatically generate these values if they don't exist in this secret. This could
  # cause confusion if users are unaware that the passwords stored here are not valid.
  admin-password: "base64 encoded kasm admin password"
  user-password: "base64 encoded kasm user password"
